<?
require $_SERVER['DOCUMENT_ROOT'].'/bitrix/modules/main/include/prolog_before.php';
global $USER;
$ID_user = $USER-> GetID();


// недвижимость
const MY_HL_BLOCK_ID_NEDVIZHIMOST = 2;
$entity_data_class_nedv = GetEntityDataClass(MY_HL_BLOCK_ID_NEDVIZHIMOST);
$rsNedv = $entity_data_class_nedv::getList(array(
    "select" => array("*"),
    "order" => array("ID" => "DESC"),
    "filter" => array("UF_USER_ID" => $ID_user,'ID'=>$_REQUEST['id'])
));
while($nedv = $rsNedv->fetch()){
    $arNedv = $nedv;
}

$UF_FLOOR_LEVEL_REQ = explode(',',$arNedv['UF_FLOOR_LEVEL_REQ']);
$arNedv['UF_FLOOR_LEVEL_OT']=$UF_FLOOR_LEVEL_REQ[0];
$arNedv['UF_FLOOR_LEVEL_DO']=$UF_FLOOR_LEVEL_REQ[1];
$arNedv['UF_FLOOR_LEVEL_NOT_FIRST']=$UF_FLOOR_LEVEL_REQ[2];
$arNedv['UF_FLOOR_LEVEL_NOT_LAST']=$UF_FLOOR_LEVEL_REQ[3];

$UF_FLOOR_LEVEL_MAX = explode(',',$arNedv['UF_FLOOR_LEVEL_MAX']);
$arNedv['UF_FLOOR_LEVEL_MAX_OT']=$UF_FLOOR_LEVEL_MAX[0];
$arNedv['UF_FLOOR_LEVEL_MAX_DO']=$UF_FLOOR_LEVEL_MAX[1];

$UF_TOTAL_AREA = explode(',',$arNedv['UF_TOTAL_AREA']);
$arNedv['UF_TOTAL_AREA_OT']=$UF_TOTAL_AREA[0];
$arNedv['UF_TOTAL_AREA_DO']=$UF_TOTAL_AREA[1];

$UF_LIVING_AREA = explode(',',$arNedv['UF_LIVING_AREA']);
$arNedv['UF_LIVING_AREA_OT']=$UF_LIVING_AREA[0];
$arNedv['UF_LIVING_AREA_DO']=$UF_LIVING_AREA[1];

$UF_KITCHEN_AREA = explode(',',$arNedv['UF_KITCHEN_AREA']);
$arNedv['UF_KITCHEN_AREA_OT']=$UF_KITCHEN_AREA[0];
$arNedv['UF_KITCHEN_AREA_DO']=$UF_KITCHEN_AREA[1];

$UF_ROOM_AREA = explode(',',$arNedv['UF_ROOM_AREA']);
$arNedv['UF_ROOM_AREA_OT']=$UF_ROOM_AREA[0];
$arNedv['UF_ROOM_AREA_DO']=$UF_ROOM_AREA[1];

$UF_CEILING_HEIGHT = explode(',',$arNedv['UF_CEILING_HEIGHT']);
$arNedv['UF_CEILING_HEIGHT_OT']=$UF_CEILING_HEIGHT[0];
$arNedv['UF_CEILING_HEIGHT_DO']=$UF_CEILING_HEIGHT[1];

$UF_PRICE_REQ = explode(',',$arNedv['UF_PRICE_REQ']);
$arNedv['UF_PRICE_OT']=$UF_PRICE_REQ[0];
$arNedv['UF_PRICE_DO']=$UF_PRICE_REQ[1];

$UF_BUILDING_YEAR_REQ = explode(',',$arNedv['UF_BUILDING_YEAR_REQ']);
$arNedv['UF_BUILDING_YEAR_OT']=$UF_BUILDING_YEAR_REQ[0];
$arNedv['UF_BUILDING_YEAR_DO']=$UF_BUILDING_YEAR_REQ[1];

$UF_AGENT_BONUS_VALUE = explode(',',$arNedv['UF_AGENT_BONUS_VALUE']);
$arNedv['UF_AGENT_BONUS_VALUE_OT']=$UF_AGENT_BONUS_VALUE[0];
$arNedv['UF_AGENT_BONUS_VALUE_DO']=$UF_AGENT_BONUS_VALUE[1];

$UF_TOTAL_AREA_REQ = explode(',',$arNedv['UF_TOTAL_AREA_REQ']);
$arNedv['UF_TOTAL_AREA_OT']=$UF_TOTAL_AREA_REQ[0];
$arNedv['UF_TOTAL_AREA_DO']=$UF_TOTAL_AREA_REQ[1];

$UF_SHARE_SIZE = explode(',',$arNedv['UF_SHARE_SIZE']);
$arNedv['UF_SHARE_SIZE_OT']=$UF_SHARE_SIZE[0];
$arNedv['UF_SHARE_SIZE_DO']=$UF_SHARE_SIZE[1];

$UF_PLOT_SQUARE = explode(',',$arNedv['UF_PLOT_SQUARE']);
$arNedv['UF_PLOT_SQUARE_OT']=$UF_PLOT_SQUARE[0];
$arNedv['UF_PLOT_SQUARE_DO']=$UF_PLOT_SQUARE[1];

$UF_PLOT_STATUS = explode('|',$arNedv['UF_PLOT_STATUS']);
$arNedv['UF_PLOT_STATUS_OTHER']=$UF_SHARE_SIZE[1];

$UF_DEPOSIT = explode(',',$arNedv['UF_DEPOSIT']);
$arNedv['UF_DEPOSIT_OT']=$UF_DEPOSIT[0];
$arNedv['UF_DEPOSIT_DO']=$UF_DEPOSIT[1];

$UF_COM_PAY = explode(',',$arNedv['UF_COM_PAY']);
$arNedv['UF_COM_PAY_OT']=$UF_COM_PAY[0];
$arNedv['UF_COM_PAY_DO']=$UF_COM_PAY[1];

$UF_ELECTRIC_POWER = explode(',',$arNedv['UF_ELECTRIC_POWER']);
$arNedv['UF_ELECTRIC_POWER_OT']=$UF_ELECTRIC_POWER[0];
$arNedv['UF_ELECTRIC_POWER_DO']=$UF_ELECTRIC_POWER[1];

$UF_PLACE_PRICE = explode(',',$arNedv['UF_PLACE_PRICE']);
$arNedv['UF_PLACE_PRICE_OT']=$UF_PLACE_PRICE[0];
$arNedv['UF_PLACE_PRICE_DO']=$UF_PLACE_PRICE[1];

$UF_FURNITURE_REQ = explode(',',$arNedv['UF_FURNITURE_REQ']);
$arNedv['UF_FURNITURE_REQ_Y']=$UF_FURNITURE_REQ[0];
$arNedv['UF_FURNITURE_REQ_N']=$UF_FURNITURE_REQ[1];

$UF_TAX = explode(',',$arNedv['UF_TAX']);
$arNedv['UF_TAX_Y']=$UF_TAX[0];
$arNedv['UF_TAX_N']=$UF_TAX[1];

$UF_BONUS = explode(',',$arNedv['UF_BONUS']);
$arNedv['UF_BONUS_OT']=$UF_BONUS[0];
$arNedv['UF_BONUS_DO']=$UF_BONUS[1];

$UF_COM_SQUARE = explode(',',$arNedv['UF_COM_SQUARE']);
$arNedv['UF_COM_SQUARE_OT']=$UF_COM_SQUARE[0];
$arNedv['UF_COM_SQUARE_DO']=$UF_COM_SQUARE[1];

$UF_CAPACITY_PASS_ELEVATORS = explode(',',$arNedv['UF_CAPACITY_PASS_ELEVATORS']);
$arNedv['UF_CAPACITY_PASS_ELEVATORS_OT']=$UF_CAPACITY_PASS_ELEVATORS[0];
$arNedv['UF_CAPACITY_PASS_ELEVATORS_DO']=$UF_CAPACITY_PASS_ELEVATORS[1];

$UF_HOISTS_CAPACITY = explode(',',$arNedv['UF_HOISTS_CAPACITY']);
$arNedv['UF_HOISTS_CAPACITY_OT']=$UF_HOISTS_CAPACITY[0];
$arNedv['UF_HOISTS_CAPACITY_DO']=$UF_HOISTS_CAPACITY[1];

$UF_CAPACITY_ELEVATORS = explode(',',$arNedv['UF_CAPACITY_ELEVATORS']);
$arNedv['UF_CAPACITY_ELEVATORS_OT']=$UF_CAPACITY_ELEVATORS[0];
$arNedv['UF_CAPACITY_ELEVATORS_DO']=$UF_CAPACITY_ELEVATORS[1];

$UF_ENTRY_PRICE = explode(',',$arNedv['UF_ENTRY_PRICE']);
$arNedv['UF_ENTRY_PRICE_OT']=$UF_ENTRY_PRICE[0];
$arNedv['UF_ENTRY_PRICE_DO']=$UF_ENTRY_PRICE[1];

$UF_COLUMN_GRID = explode(',',$arNedv['UF_COLUMN_GRID']);
$arNedv['UF_COLUMN_GRID_OT']=$UF_COLUMN_GRID[0];
$arNedv['UF_COLUMN_GRID_DO']=$UF_COLUMN_GRID[1];

$UF_MONTH_PROFIT = explode(',',$arNedv['UF_MONTH_PROFIT']);
$arNedv['UF_MONTH_PROFIT_OT']=$UF_MONTH_PROFIT[0];
$arNedv['UF_MONTH_PROFIT_DO']=$UF_MONTH_PROFIT[1];

$UF_DISPLAY_WINDOWS_REQ = explode(',',$arNedv['UF_DISPLAY_WINDOWS_REQ']);
$arNedv['UF_DISPLAY_WINDOWS_Y']=$UF_DISPLAY_WINDOWS_REQ[0];
$arNedv['UF_DISPLAY_WINDOWS_N']=$UF_DISPLAY_WINDOWS_REQ[1];

$UF_LEGAL_ADDRESS = explode(',',$arNedv['UF_LEGAL_ADDRESS']);
$arNedv['UF_LEGAL_ADDRESS_Y']=$UF_LEGAL_ADDRESS[0];
$arNedv['UF_LEGAL_ADDRESS_N']=$UF_LEGAL_ADDRESS[1];

$UF_COMMISSIONS_AGENT = explode(',',$arNedv['UF_COMMISSIONS_AGENT']);
$arNedv['UF_COMMISSIONS_AGENT_OT']=$UF_COMMISSIONS_AGENT[0];
$arNedv['UF_COMMISSIONS_AGENT_DO']=$UF_COMMISSIONS_AGENT[1];

$UF_COMMISSIONS_RENT = explode(',',$arNedv['UF_COMMISSIONS_RENT']);
$arNedv['UF_COMMISSIONS_RENT_OT']=$UF_COMMISSIONS_RENT[0];
$arNedv['UF_COMMISSIONS_RENT_DO']=$UF_COMMISSIONS_RENT[1];

$UF_SECURITY_DEPOSIT = explode(',',$arNedv['UF_SECURITY_DEPOSIT']);
$arNedv['UF_SECURITY_DEPOSIT_OT']=$UF_SECURITY_DEPOSIT[0];
$arNedv['UF_SECURITY_DEPOSIT_DO']=$UF_SECURITY_DEPOSIT[1];

$UF_HOLIDAYS_RENT_REQ = explode(',',$arNedv['UF_HOLIDAYS_RENT_REQ']);
$arNedv['UF_HOLIDAYS_RENT_Y']=$UF_HOLIDAYS_RENT_REQ[0];
$arNedv['UF_HOLIDAYS_RENT_N']=$UF_HOLIDAYS_RENT_REQ[1];

$UF_OPERATION_COSTS = explode(',',$arNedv['UF_OPERATION_COSTS']);
$arNedv['UF_OPERATION_COSTS_Y']=$UF_OPERATION_COSTS[0];
$arNedv['UF_OPERATION_COSTS_N']=$UF_OPERATION_COSTS[1];

$UF_OCCUPIED = explode(',',$arNedv['UF_OCCUPIED_REQ']);
$arNedv['UF_OCCUPIED_Y']=$UF_OCCUPIED[0];
$arNedv['UF_OCCUPIED_N']=$UF_OCCUPIED[1];

$UF_UTILITY_PAY_INCLUDED_REQ = explode(',',$arNedv['UF_UTILITY_PAY_INCLUDED_REQ']);
$arNedv['UF_UTILITY_PAY_INCLUDED_REQ_Y']=$UF_UTILITY_PAY_INCLUDED_REQ[0];
$arNedv['UF_UTILITY_PAY_INCLUDED_REQ_N']=$UF_UTILITY_PAY_INCLUDED_REQ[1];



echo json_encode($arNedv);
